# Generated by Django 3.2.23 on 2024-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='Link',
        ),
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(upload_to='media/banner_imgs'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Main_category',
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
